// Generated by FigmaWriter — paste into Figma ▶ Plugins ▶ Console
// Node : 'MyFrame'
// Type : frame
// Date : 2026-03-01 09:02:17
//
// Steps:
//   1. Open Figma
//   2. Plugins ▶ Development ▶ Open Console  (Cmd+Opt+I)
//   3. Paste this script and press Enter
//
(async () => { try {
  await figma.loadFontAsync({family:"Inter",style:"Regular"});
  const _par = figma.currentPage;
  const n0 = figma.createFrame();
  _par.appendChild(n0);
  n0.name = "MyFrame";
  n0.x = 0.0; n0.y = 0.0;
  n0.resize(400,300);
  n0.fills = [{type:'SOLID',color:{r:0.2902,g:0.5647,b:0.8863,a:1.0000},opacity:1.0000,visible:true}];
  const n1 = figma.createText();
  n0.appendChild(n1);
  n1.name = "Click me";
  n1.x = 0.0; n1.y = 0.0;
  n1.fontName = {family:"Inter",style:"Regular"};
  n1.fontSize = 14.0;
  n1.textAlignHorizontal = "LEFT";
  n1.textAutoResize = "WIDTH_AND_HEIGHT";
  n1.characters = "Click me";
  n1.fills = [{type:'SOLID',color:{r:0.0000,g:0.0000,b:0.0000,a:1.0000},opacity:1.0000,visible:true}];
  return {success:true,nodeId:n0.id,nodeName:n0.name};
} catch(e) { return {success:false,error:String(e)}; }
})();